### ISSUE TITLE
SoulSilver randomly crashing

### ISSUE THREAD

**Issue by Hayes231** [ahezard/nds-bootstrap#129]
SoulSilver works, loading times are kinda slow. Only thing wrong is that the game crashes seemingly randomly. 2 times it crashed during loading times to a black screen. Once it crashed while walking through tall grass to a red screen on top, with the normal bottom screen and music continuing to play. This was on the official release, I'm switching to unofficial now to see if it works

**Comment by Shishire** [comment]
I've got the same problem with Heart Gold. It mostly works, but every couple of screen transitions (fade-to-black, unfade) gets stuck part way through (fade-to-black, stuck). I've noticed that if the music keeps playing, rather than fading as it should, then it's guaranteed to not fade back in. 

I've taken to saving my game regularly, and noticed that every few saves, it will finish saving, the throw a red upper screen with a few white dots on it. Reloading from the save is successful.

I've tried both release and unofficial, with no significant difference in behavior.

**Comment by Robz8** [comment]
Try the AP patches in here, to fix the consistent (not random) crashes.
https://www.odrive.com/s/8443cc3a-862e-41d7-b064-09378f79f6b3-5965a89a

**Comment by MistieKitteh** [comment]
Even patched the same issue is present. Game 'freezes' (music, black screen, doesn't finish transition) during zone transition. Though ive noticed that on the zone before the freeze your models will be bugged. So i guess you know when to save and restart the game /shrug

**Comment by Shishire** [comment]
Having tried the patches, I no longer see the major stability issues that I was seeing before, but like @MistieKitteh, I still see the occasional visual corruption -> transition failure issue.

**Comment by Robz8** [comment]
Next version will fix the issues.

**Comment by Pokecreatorfr** [comment]
I have the same problem with the lastest version on my DSI .

**Comment by JonArcherII** [comment]
Heartgold and Soulsilver play practically flawlessly on the current release on my DSi, I would recommend asking for help in the discord first before necro-posting a very old (and closed) issue.
