### ISSUE TITLE
Travis Builds failing

### ISSUE THREAD

**Issue by NoMod-Programming** [ahezard/nds-bootstrap#192]
https://travis-ci.org/ahezard/nds-bootstrap/builds

Last commit to build was c56a21dd59bd1e2b977653c73f8c33d8d3b4ee02

**Comment by c-schuhmann** [comment]
Thats because of the transition from the DevkitPro installation script to DevkitPro-pacman.

**Comment by ahezard** [comment]
.travis.yml have to rewritten indeed for DevkitPro-pacman.

**Comment by ahezard** [comment]
I found this example that can probably be adpated for us https://github.com/Maschell/libgui/blob/master/.travis.yml

**Comment by Celti** [comment]
The immediate issue is that the generated `cardengine_armX.bin.o` files (and their companion `cardengine_armX_bin.h` files) aren't getting generated properly, because devkitARM on Linux does *not* come with bin2s by default.

I can make local Linux builds work by installing the following with pacman:
```
dkp-linux/devkitARM
dkp-linux/general-tools
dkp-linux/ndstool
dkp-linux/dstools
dkp-libs/libnds
dkp-libs/libfat-nds
```

Travis seems to be much the same.

**Comment by ahezard** [comment]
So it is working now. Thanks for your contribution.
