### ISSUE TITLE
Build files cleanup

### ISSUE THREAD

**Issue by Exagone313** [ahezard/nds-bootstrap#289]
Following #262, I'd like to make some cleanup to your build files.

* I see that you're copying files between directories, using directory names as targets, etc... It adds complexity to the build.
* It could either have one build directory, or one per part, or not use any, but it's not consistent (see `data` directory).
* The `cardengine_arm[79]` parts cannot be built with more than one job (`-j1`). This is solved by having *clear* dependencies between each part, so it waits before running sub-commands.
* A lot of commands are hidden, it does not help for debugging.

I want to clean this up, but I don't really understand the dependencies between each part of the app, especially for the card engines. If you could tell me in what order things are supposed to be built and what part depends on what other parts (and the files it produces), it would help.
But if you feel like it should stay like that and you can maintain the project as-is, tell me and I won't change anything.

**Comment by ahezard** [comment]
I understand the limitations you express are anoying. Pull request are welcome. Otherwise it is currently working and I have no time for that.

About the dependencies :
arm9 depends on bootloader (produces load.bin file) that depends on card_engine_arm7 and card_engine_arm9 (bins files embedded into the load.bin which itself is embedded into the nds-bootstrap.elf arm9 file.
nds-bootstrap.elf arm7 file and arm9 file are used to produces the nds-bootstrap.nds final file

**Comment by Exagone313** [comment]
Will check next week, they made a great wotk so it's probably done.

**Comment by dubbz82** [comment]
Since it's been quite some time, is this still an issue, or should this be closed out?

**Comment by Exagone313** [comment]
Just keep it low priority, maybe someday...
