### ISSUE TITLE
Regression so far. :o

### ISSUE THREAD

**Issue by hectortillo** [ahezard/nds-bootstrap#33]
Now i cant run some games as
Netroid Prime Hunters 
Pokemon Explorers of Sky
Mario DS
Castlevania Dawn of Sorrow (before had badly graphical glitches)
Caatlevania Portrait of Ruin
Mario Kart
WarioWate 

All of them are EUR region but some as Castlevanias and Pokemon i have them in regions US and Eur. 

Thanks for all your hard work ahezard. :D you are incredible. :) thanks to all who are involved in this project :) if i can do something to help. Count with me.  :)  (excuse me for my bad english)  
Again some many thanks :)  

I have disabled the lock Arm9 scfg_ext .   Im in TWloader 3.0.2. :)

**Comment by ApacheThunder** [comment]
I've personally tested Mario 64 DS and Mario Kart (both US region titles FYI) and they work. Did you copying the roms over again? They might have been corrupted by an older version of bootstrap. There was an old bug that used to cause bootstrap to write the save over the rom. This has since been fixed so if you haven't recopies any of your roms since then, I highly suggest you do. Metroid has not ever worked as far as I can tell and I have not tested the other games you mentioned. :P

**Comment by Robz8** [comment]
You should enable VRAM boost, if it isn't.

**Comment by hectortillo** [comment]
Vram boost is enabled :o. I will copy again my Roms. And will try again.  @ApacheThunder. I have noticed that bug of the roms before and i only had since then the official commit. But i will try to copy again my roms. I only updated from 0.2.0 to this pre release 0.3.0 alpha 1 :)    thanks. :)

**Comment by hectortillo** [comment]
its not the games :o i have redownloaded it and try to run but no was succesful i will uninstall all and try form the sratch to see if it was the problem :)

**Comment by hectortillo** [comment]
now it works :) its the 2nd time i have to delete all and reinstalll  :( excuse me and thanks :) i will close the issue :) the next time i will do this before posting :) thanks :)
