### ISSUE TITLE
Etrian Odyssey 3

### ISSUE THREAD

**Issue by jellyoooo** [ahezard/nds-bootstrap#363]
When I set sail in Inver Port, the game get stuck in a black screen, but the background music is still playing.

**Comment by diuXd9gfdwco2P** [comment]
It's most likely a rom bug.
I've had a similar issue when using the Indomitable limit skill (and only that one, the others work without issue). The game freezes completely with the background music still playing. When I tried another rom (the NukeThis release), the skill worked just fine.
I didn't try sailing as I'm still in the very beginning of the game but since the bug I've had is almost similar , then I guess trying the NukeThis release will fix your problem as well.

**Comment by jellyoooo** [comment]
I tried the Nukethis release, but it didn't fix the problem for me. Also, when I use limit skills, the game freezes with the music still going.

**Comment by jellyoooo** [comment]
It's fixed now. I just used OpenPatch. It was the ap that was causing the game to freeze.

**Comment by diuXd9gfdwco2P** [comment]
Hey there,
I got to the point where I could sail and I just wanted to confirm that the game froze as well with the NukeThis Release.
I'll use OpenPatch then. Thanks for the tip.

**Comment by jellyoooo** [comment]
Np
