### ISSUE TITLE
Pokemon White 2 Hanging When Using Potion

### ISSUE THREAD

**Issue by 7MoonsMusic** [ahezard/nds-bootstrap#380]
So when I'm playing pokemon white 2, I go into the bag like usual and use a potion on one of my pokemon. however afterwards when I press b to go back, the game fades to black and the game/sound hangs.

**Comment by Robz8** [comment]
Sounds like the game isn't AP-patched.

**Comment by Kalanyr** [comment]
This error does not occur on AP Patched White 2 Rom (at least on nightly: https://github.com/ahezard/nds-bootstrap/commit/261eadaa1c357936fb2ba2c9f3669c8321ce3a76  )

There does seem to be some issues probably caused by Async Prefetch which causes crashes which lead to need to shut down error messages when in battle.

**Comment by NightYoshi370** [comment]
@7MoonsMusic AP Patch your ROM.
If you still get errors, let us know. For now, this is closed
