### ISSUE TITLE
Pokémon Black and Black 2 experience new frequent hiccups with the last release

### ISSUE THREAD

**Issue by Mr-Gela** [ahezard/nds-bootstrap#390]
I've tested on both clean Black 2 and Blaze Black 2 and they both has those hiccups, so it's not due to the romhack.
These hiccups weren't present in the release fixing Blaze Black 2 provided by @piratesephiroth or v0.11.0. 
The hiccups are mostly present in the overworld but happen a bit less frequently during battles as well.

Tested Sacred Gold just to make sure it's fine and it is. So it's just BW/BW2 and it's hacks.

My nds-bootstrap ini:

> [NDS-BOOTSTRAP]
> NDS_PATH = sd:/roms/clean/6149 - Pokemon - Black Version 2 (U) (frieNDS).nds
> SAV_PATH = sd:/roms/clean/6149 - Pokemon - Black Version 2 (U) (frieNDS).sav
> DONOR_SDK_VER = 5
> BOOTSTRAP_PATH = sd:/_nds/nds-bootstrap.nds
> ROMREAD_LED = 0
> BOOST_CPU = 1
> DEBUG = 0
> LOCK_ARM9_SCFG_EXT = 0
> PATCH_MPU_REGION = 0
> PATCH_MPU_SIZE = 0
> CONSOLE_MODEL = 2
> LANGUAGE = -1
> ASYNC_PREFETCH = 1
> GAME_SOFT_RESET = 0
> NTR_TOUCH = 0
> LOADING_SCREEN = 1
>

**Comment by Mr-Gela** [comment]
Just letting you know this is still present in v0.11.2 and with BOOST_VRAM enabled.

**Comment by Kalanyr** [comment]
What do you mean by hiccup ? Is it the bit of lag when a new map part is loaded inside an area ?  And it doesn't occur again within that area once you've crossed the loading point from each side once ? 

Because that's been present to some extent in every build I've tried. 

If that's what you mean I'll grab 11.0 and have a look and see if it's absent from that version.

**Comment by Kalanyr** [comment]
I just grabbed 0.11.0 and compared it to the lastest (self-compiled) nightly  (with sound fix /VRAm Boost / TWL Speed / Better Audio all on) (https://www.dropbox.com/s/ewtv7k0qodou8yd/nds-bootstrap-nightly.nds?dl=0) built from https://github.com/ahezard/nds-bootstrap/commit/261eadaa1c357936fb2ba2c9f3669c8321ce3a76 

And the lag between the map subarea loading seems roughly the same to me.  Maybe I'm misidentifying the issue or it was fixed in the last 4 commits  ?

**Comment by ihadtomakeanaccountforthis** [comment]
Not sure if it's the exact same thing he's talking about but I've been having something similar to hiccups/stutters right out the gate (O3DS, 0.11.2, VRAM on and off, TWL speed). The game will freeze for a second or two while I'm moving around and then continue. Didn't even get to leave Nuvema before it happened like 4 times (ie. it's not the subarea lag like the rest of the games). I just played through Platinum and Soul Silver in full without anything like that happening so it's definitely an issue with Black.

**Comment by Kalanyr** [comment]
I think this is the best report to use for this. The isGameLaggy check has helped with the hiccups on in area loading in Pokemon Black (and I assume B2/W/W2 since the games seem to be effected in identical ways on this and a lot of other issues)  but it hasn't resolved the issue entirely, the stutter is still present though much reduced.

**Comment by NaturalHarmonia** [comment]
Try turning Wireless off on your 3DS. It might help a bit.

**Comment by ahezard** [comment]
This issue seems to be fixed with the improvement made in the non_blocking_io branch currently under internal test

**Comment by edo9300** [comment]
I tested with pokemon black 2 and now the map transitions are very smooth

**Comment by ahezard** [comment]
Fixed in v0.14.1
