### ISSUE TITLE
Zelda Phantom Hourglass Randomly freezes with black screen

### ISSUE THREAD

**Issue by jotape90** [ahezard/nds-bootstrap#429]
It happens at the temple of the ocean king, when Link meets Linebeck. Game stays on black screen.

**Comment by xdcdx** [comment]
I'was experiencing the same problem: random crashes (black screen) after the main intro, or when entering islands, or boarding ships. I tried downgrading to v0.11.2 (I saw it suggested by somebody online) and it seems to work better with that version. I cannot confirm no crashes yet, because they're pretty random, but fingers crossed.

**Comment by jmandawg** [comment]
Same issue, black screen after intro...

**Comment by Plausible0Bug** [comment]
It seemed as of https://github.com/ahezard/nds-bootstrap/releases/tag/v0.14.0RC1

I can play this game properly.

I used to be stuck right after shield purchasing and later entering the shrine for the phantom sand.

Now I'm at the place where I search for a way to pass the fog, no problem so far.

I'm using twilight menu on my n3ds with luma3ds.
