### ISSUE TITLE
Pokémon Mind Crystal random issues

### ISSUE THREAD

**Issue by kxkxrxtx** [ahezard/nds-bootstrap#444]
So this hackrom seems to work perfectly, but every now and then crashes, freezes or just turns into a black screen every 15-20 minutes when starting a trainer or wild battle, entering to another location or talking to people. 

For those who don't know, the base rom version used is french HGSS (EUR) and another user of the community, Rodygo, made an english patch translation (you can find it in the same thread).

Now I'm using this on an O3DS with the latest bootstrap and TwilightMenu++ versions and current version of the hack is 3.0.2. So anyone who knows how to run this without any issue? Thanks in advance.

Link to hackrom: https://www.pokecommunity.com/showthread.php?t=393373

**Comment by dubbz82** [comment]
You MAY be able to use an existing HG/SS AP patch with an delta patcher that's capable of ignoring checksum mismatches.  This is how it was done for an English translation for ace Attorney investigations and it's worked well.  You may have to do some trial and error though because the AP patches may patch different areas of the ROM depending on which one the author actually used as a base

**Comment by brianmluo** [comment]
Doesn't seem to be able to save? Every time I reset the game, it goes right back to the beginning.

**Comment by RocketRobz** [comment]
Did you move your save file to `saves`?
It should be in the same folder as the ROMs.
I'm able to use saves just fine.

**Comment by brianmluo** [comment]
Yep, they're both in the same folder. I tried using the save on an emulator and it worked properly. Using TwilightMenu, the game acts as if the save isn't there. 
![trouble](https://user-images.githubusercontent.com/46423599/50739352-0a387f80-11ad-11e9-8a17-d13fa320d408.PNG)

**Comment by RocketRobz** [comment]
No, I mean a folder called `saves`.
