### ISSUE TITLE
Ace Attorney Investigations 2 Constantly crashes after case 2

### ISSUE THREAD

**Issue by Sonic4999** [ahezard/nds-bootstrap#458]
Ok, I know about the AP patch needed. So using that and the translation, I tried doing a runthrough of the game, and got to the end of case 2. At the last part of the case, it freezes, and I can't continue.

I've actually tried using some saves from another emulator (as in the nds saves, not the emulator's) to bypass this, however, once you get into case 3, the game will constantly crash over and over, which makes it basically impossible to play the game.

Suggesting how I just updated today everything should be up to date.

**Comment by aphirst** [comment]
Are you able to share a save file at the point where the issue can be easily reproduced?

**Comment by Sonic4999** [comment]
https://www.dropbox.com/s/ejtxe1p22umop1b/The%20save.sav?dl=0

I think this is probably at the point where it crashes (it could be a bit ahead, though I doubt).

**Comment by PsikoBlock** [comment]
If your ROM has a sha256 checksum of 801baeb2a153bb51bc75ff44b2b1d47898099c80cfd635420f9b304f3b06d1bd and a size of 41 943 040 bytes, it's patched with the broken AP patch for an older version of the translation (AP1-5beta). DMSalesman in the original thread has created a new patch for the Final V2 release: https://gbatemp.net/threads/ace-attorney-investigation-2-prosecutors-path-final-release.367451/page-47#post-8282054
Try patching your ROM file with this instead of the broken one. It should not change the file size of 45 165 392 bytes, but fix the garbled text.

**Comment by aphirst** [comment]
@PsikoBlock Can you also confirm the sha256 sum of the correctly patched final release?

**Comment by Sonic4999** [comment]
If I did everything correctly, it should be:
ccfcd45cd4bbe9894d5364facc4858cea4b539e4cb2505d03f8da4e0df133525
Of course it may be different suggesting I'm not the smartest.

**Comment by aphirst** [comment]
Thanks for the confirmation, @Sonic4999 . I notice that in the thread OP they don't seem to yet include that V2 patch, which suggests it's not quite yet "official" ?

**Comment by Sonic4999** [comment]
@aphirst yeah, it doesn't seem to be official, and I don't think it'll ever be. I still think that it should be on the spreadsheet so people don't freeze at what I may say is the very end of a decently long case.

**Comment by DMSalesman** [comment]
Patch author here. No, the patch is not official, but it works. Glad it was useful to you.
