### ISSUE TITLE
Add screenshot-to-SD functionality.

### ISSUE THREAD

**Issue by mariomadproductions** [ahezard/nds-bootstrap#71]
Would this be possible? I know it is possible for DS software to take screenshots of itself, and there should be some way to write to the SD, even if indirectly.

**Comment by Gericom** [comment]
There are most likely a couple of problems with this. First of all only the main screen can be screenshotted. Secondly there needs to be vram available to write the screenshot to in such a way that the picture is not distorted because the vram is used for writing the screenshot to. And games that make use of this function might start acting weird when this is done.

**Comment by mariomadproductions** [comment]
I may be completely misunderstanding, but couldn't something other than vram be used to write the screenshot to? Or would that end up crashing the game, meaning it would end up not being written to the SD card? What if the DSi extended memory was enabled?

**Comment by Gericom** [comment]
It's physically not possible. You can only select vram block A, B, C or D as destination for the capture. The display controller can not access anything else than vram.

**Comment by mariomadproductions** [comment]
Okay, so you are saying that only the main screen can be taken - and the screenshot would use up VRAM, causing some (many?) games to glitch. Could a solution to that be some sort of save state that was taken before the screenshot was taken, to restore the game back to before the VRAM was glitched up? Otherwise I guess you would have to reset?

**Comment by Gericom** [comment]
Well, of course you could first save the vram you're gonna overwrite and then restore it afterwards, but there are situations in which vram block A, B, C and D are all used for the main screen. So destroying any of these blocks would distort your capture result no matter what. In games that have at least one of these blocks not mapped to the main screen, but to the sub screen, lcdc, or not at all, it would be somewhat possible.

**Comment by ahezard** [comment]
So gericom did a very good analysis. This is almost impossible.

**Comment by ApacheThunder** [comment]
There is one way you could get screenshots. You hijack the arm11 twlBg thread somehow. Of coarse since Arm11 probably doesn't have direct SD access you'd have to have some way of getting the screenshot to SD. Perhaps via an arm7 + arm9. You'd have to play hot potato basically. Arm11 twlbg screen caps the output frame and saves it somewhere only it has access to. Then you'd have to call arm9 to access that by somehow getting twlBg to give it the screenshot data. Then you'd have to pass that to arm7.

Might be doable, but you'd have to reverse twlBg first. Good luck, because outside of that it ain't happening. :P

**Comment by mariomadproductions** [comment]
Thanks for the explanations. I think I might be getting a capture card then :P

**Comment by mariomadproductions** [comment]
A potential way around the "where to put the screenshot" could be solved by outputting the data via sound, using [Kansas City standard/Byte standard](https://en.wikipedia.org/wiki/Kansas_City_standard) - you'd use an audio cable to record the output with a PC.
