### ISSUE TITLE
Suggestion: Make the creation of the fat table set per-game

### ISSUE THREAD

**Issue by IrisHeartCPU** [ahezard/nds-bootstrap#878]
Suggestion: Make the creation of the fat table that is created by every game and stored in /_nds/nds-bootstrap/fatTable/ "set per-game" like the widescreen instead of choosing if wanting to create or read it on the settings menu. I think with that, instead of putting on ON or OFF and letting a posibility of making corruption on the microsd if ON, and making some games not work if OFF, that will be useful, because we will select only in what games we want the fat table of 512kb want to be created (the games that need it) and it will reduce the probability of corruption of the MicroSD.

**Comment by Dartz150** [comment]
I didn't knew that it caused SD corruption, is there any specific reason for that to happen? Also, I agree, but it could be tiresome for 3DS users because everytime you soft reboot a game, the "bootsrap" screen appears, adding more loading time to the already existing. Actually this gives me a good idea for a sugested feature, but I will open another issue for that.

**Comment by IrisHeartCPU** [comment]
It says something like this in the settings of twilight menu: "Turn it off if you start to see corruption", i don't know the reason why this happens, but i know that i've read

**Comment by NightYoshi370** [comment]
Not something that's decided by nds-bootstrap. This should be on the TWiLight Menu++ repository.
Closing...

**Comment by IrisHeartCPU** [comment]
Sorry, i only tried to help, and didn't know my suggestion should be on that repository. But done, is not on TWiLight Menu++ repository.

**Comment by NightYoshi370** [comment]
Nah, you're fine. We'll just wait and see I suppose.
Thanks for moving it to the correct repository
