### ISSUE TITLE
Pokemon Black 2 (EUR) Game card doesnt sound

### ISSUE THREAD

**Issue by Lumiazaine** [ahezard/nds-bootstrap#984]
**Your console:**  DSI XL
**Launch Method:**  Lastest version
**Version used:** 
**Flashcart used:**  Pokemon Black 2 (EUR)
**Game tested/used/applicable:** 

**Expected Behavior:** 
**Actual Behavior:** 

### Steps to reproduce

Just start the game

**Comment by SleepyLark** [comment]
Are you trying to launch the physical cart?  Because if you are i know that the "slot1launch.srldr" (the file used to launch slot-1 cartridges in Twilight Menu) broke in the latest version so you have to either downgrade that file or change the boot option in the Twilight Menu settings to either "direct" or "Unlaunch"

**Comment by takeshineale128** [comment]
this has been fixed and update to the latest twilight menu version (v16.0.0)
